# Generated by Django 3.2.9 on 2021-11-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
